format = """
[](#191970)\
$os\
$username\
[](fg:#191970 bg:#002395)\
$conda\
[](fg:#002395 bg:#00416a)\
$directory\
[](fg:#00416a bg:#16537e)\
$git_branch\
$git_status\
[](fg:#16537e bg:#1560bd)\
$kubernetes\
[](fg:#1560bd bg:#3366ff)\
$time\
[ ](fg:#3366ff)\
$aws
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#191970"
disabled = true # Disabled by default

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#191970"
style_root = "bg:#191970"
format = '[☥ ($user) ☥ ]($style)'
disabled = false

[conda]
symbol = "󰌠 "
style = "bg:#002395"
format = '[ $symbol ($environment) ]($style)'
disabled = false

[directory]
style = "bg:#00416a"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "bg:#16537e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#16537e"
format = '[$all_status$ahead_behind ]($style)'

[kubernetes]
symbol = "⎈ "
style = "bg:#1560bd"
format = '[ $symbol ($context) | ($namespace) ]($style)'
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#3366ff"
format = '[   $time ]($style)'

# No custom format for aws, default one is cool

[character]
success_symbol = '[❯](bold #DDDDDD)'
error_symbol = '[❯](bold red)'
