format = """
[](#0c0909)\
$os\
$username\
[](fg:#0c0909 bg:#110707)\
$conda\
[](fg:#110707 bg:#220707)\
$directory\
[](fg:#220707 bg:#370606)\
$git_branch\
$git_status\
[](fg:#370606 bg:#4a0606)\
$kubernetes\
[](fg:#4a0606 bg:#740a0a)\
$time\
[ ](fg:#740a0a)\
$aws
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#0c0909"
disabled = true # Disabled by default

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#0c0909"
style_root = "bg:#0c0909"
format = '[☥ ($user) ☥ ]($style)'
disabled = false

[conda]
symbol = "󰌠 "
style = "bg:#110707"
format = '[ $symbol ($environment) ]($style)'
disabled = false

[directory]
style = "bg:#220707"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "bg:#370606"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#370606"
format = '[$all_status$ahead_behind ]($style)'

[kubernetes]
symbol = "⎈ "
style = "bg:#4a0606"
format = '[ $symbol ($context) | ($namespace) ]($style)'
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#740a0a"
format = '[  $time ]($style)'

# No custom format for aws, default one is cool

[character]
success_symbol = '[❯](bold #DDDDDD)'
error_symbol = '[❯](bold red)'
